In [2]:
import numpy as np

a = np.array([[1,5,6], [9, 8, 3]])
print(a.shape, ' 2 rowns and 3 columns')

(2, 3)  2 rowns and 3 columns


In [4]:
ppm = np.array([[ 20.80, 20.71, 21.72, 18.81],
 [ 19.91, 18.42, 20.73, 20.32],
 [ 17.32, 21.74, 23.19, 19.98]])

print(np.shape(ppm))

(3, 4)


In [ ]:
values = np.zeros((3, 2), dtype = int)
print(values)

values_1 = np.zeros((3,2), dtype='l')
print(values_1)

[[0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]]


In [17]:
#first way#
factors = np.array([[0,1,2,3], [4, 5, 6, 7]], dtype = float)
print(factors)

#second way#
factors_1 = np.reshape(np.arange(8.0), (2,4))
print(factors_1)



[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]
[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]


In [21]:
#one way#

sevens = np.full((3,5), 7, dtype=int)
print(sevens)

#second way#
sevens_1 = np.ones((3, 5), dtype=int) * 7
print(sevens_1)

#third way#
sevens_2 = np.zeros((3, 5), dtype=int) + 7
print(sevens_2)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
factors = np.reshape(np.arange(8.0), (2,4))
print(factors)

values = factors[1, 2]
print(values)

[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]
6.0


In [23]:
first_row = factors[0, :]
print(first_row)

[0. 1. 2. 3.]


In [24]:
subset = factors[:, 1:3]
print(subset)

[[1. 2.]
 [5. 6.]]


In [31]:
#second way#
factors = np.reshape(np.arange(8.0), (2,4))
print(factors)

[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]


In [28]:
factors[0, 0:3] = factors [1, 1:4]
print(factors)

[[5. 6. 7. 3.]
 [4. 5. 6. 7.]]


In [30]:
factors[0, 0:3] = factors [1, 1:]
print(factors)

[[5. 6. 7. 3.]
 [4. 5. 6. 7.]]


In [32]:
factors[0, 0:3] = factors [1, -3:]
print(factors)

[[5. 6. 7. 3.]
 [4. 5. 6. 7.]]


In [33]:

ppm = np.array([[20.80, 20.71, 21.72, 18.81],
                [19.91, 18.42, 20.73, 20.32],
                [17.32, 21.74, 23.19, 19.98]])

ppb = ppm * 1000
print(ppb)

[[20800. 20710. 21720. 18810.]
 [19910. 18420. 20730. 20320.]
 [17320. 21740. 23190. 19980.]]


In [ ]:
data1 = np.array([[1, 2, 3],
                  [4, 5, 6]])

data2 = np.array([[7, 8, 9],
                  [10, 11, 12]])

# Average between corresponding elements
avg_between_both = (data1 + data2) / 2
print(avg_between_both)

[[4. 5. 6.]
 [7. 8. 9.]]


In [37]:
##first way##

data3 = np.array([[3, 8, 2],
                  [10, 5, 7],
                  [6, 4, 9]])

max_data3 = np.max(data3)
print("Max. with NumPy:", max_data3)

##second way#3

max_data3=data3[0,0]
for i in range(data3.shape[0]):        # loop through the rows
    for j in range(data3.shape[1]):    # loop through the columns
        if data3[i, j] > max_data3:    # compare current element
            max_data3 = data3[i, j]    # update the maximum

print("Max. with loops:", max_data3)

Max. with NumPy: 10
Max. with loops: 10
